### ISSUE TITLE
Can't force to find

### ISSUE THREAD

**Issue by danbasko** [soxoj/socid_extractor#2]
Hello. Could you help me with this problem? What my mistake with using this?
`>>> /home/danbasko/Desktop/socid_extractor-master/socid_extractor.py https://twitter.com/orika_art
  File "<stdin>", line 1
    /home/danbasko/Desktop/socid_extractor-master/socid_extractor.py https://twitter.com/orika_art
    ^
SyntaxError: invalid syntax
>>> ./socid_extractor.py https://twitter.com/orika_art
  File "<stdin>", line 1
    ./socid_extractor.py https://twitter.com/orika_art
    ^
SyntaxError: invalid syntax
`

**Comment by soxoj** [comment]
Please make sure you have installed Python 3.

I see also that the Twitter page data format was changed. This is not related to your problem directly, but you won't be able to get info soon until I [deal with the problem](#3).
